config/routes.rb
NestedResources::Application.routes.draw do
  get "home/index"

  root :to => 'home#index'
  
  resources :outresources do
    resources :inresources
  end
  

end

app/models/inresource.rb
class Inresource < ActiveRecord::Base
  belongs_to :outresource
  attr_accessible :descr, :name
end

app/models/outresource.rb
class Outresource < ActiveRecord::Base
  attr_accessible :descr, :name
  has_many :inresources, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inresources_controller.rb
class InresourcesController < ApplicationController
  
  def index #/outresources/2/inresources
    @outresource = Outresource.find(params[:outresource_id])
    @inresources = @outresource.inresources.all #tutte le risorse interne a quella esterna
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inresources }
     end 
  end
  
  def new #/outresources/2/inresources/new
    @outresource = Outresource.find(params[:outresource_id])
    @inresource = @outresource.inresources.new
    
    #redirect_to new_outresource_inresource(@outresource)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inresources }
    end
  end
  
  def create
    @outresource = Outresource.find(params[:outresource_id])
    @inresource = @outresource.inresources.create(params[:inresource])
    redirect_to outresource_inresources_path(@outresource)
  end
  
  def show
    #@outresource = Outresource.find(params[:outresource_id])
    #@inresource = @outresource.inresources.find(params[:id])
    @inresource = Inresource.find(params[:id]) #questa riga sostituisce le due sopra
    respond_to do |format|
      format.html #show.html.erb
      format.json { render json: @inresource }
    end
  end

  def edit
    @inresource = Inresource.find(params[:id])
  end
  
  def update
    @inresource = Inresource.find(params[:id])

    respond_to do |format|
      if @inresource.update_attributes(params[:inresource])
        format.html { render 'show', notice: 'Risorsa Interna was successfully updated.' }
        format.json { render json: @inresource }
      else
        format.html { render action: "edit" }
        format.json { render json: @inresource.errors, status: :unprocessable_entity }
      end
    end
  end
    
  
  def destroy
    @outresource = Outresource.find(params[:outresource_id])
    @inresource = @outresource.inresources.find(params[:id])
    @inresource.destroy
    redirect_to outresource_inresources_path(@outresource)
  end
  
  
end

app/controllers/outresources_controller.rb
class OutresourcesController < ApplicationController
  
  def index
    @outresources= Outresource.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outresources }
     end 
  end

  
  def new
    @outresource = Outresource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outresource }
    end
  end
  
  def edit
    @outresource = Outresource.find(params[:id])
  end
  
  def create
    @outresource = Outresource.new(params[:outresource])

    respond_to do |format|
      if @outresource.save
        format.html { redirect_to @outresource, notice: 'Risorsa Esterna was successfully created.' }
        format.json { render json: @outresource, status: :created, location: @outresource }
      else
        format.html { render action: "new" }
        format.json { render json: @outresource.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @outresource = Outresource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outresource }
    end
  end
  
  def update
    @outresource = Outresource.find(params[:id])

    respond_to do |format|
      if @outresource.update_attributes(params[:outresource])
        format.html { redirect_to @outresource, notice: 'Risorsa Esterna was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outresource.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @outresource = Outresource.find(params[:id])
    @outresource.destroy

    respond_to do |format|
      format.html { redirect_to outresources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inresources_helper.rb
module InresourcesHelper
end

app/helpers/outresources_helper.rb
module OutresourcesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Pagina Iniziale</p>

<h1>Collegamenti:</h1>
<%= link_to "Collegamento a Risorse Esterne", outresources_path %>

app/views/inresources/_form.html.erb
<%= form_for([@outresource, @outresource.inresources.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descr %><br />
    <%= f.text_area :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inresources/_inresource.html.erb
  <p>
    <b>Nome Risorsa Interna:</b>
    <%= inresource.name %>
  </p>
 
  <p>
    <b>Descrizione Risorsa Interna:</b>
    <%= inresource.descr %>
  </p>
  
  <p>
  <%= link_to 'Destroy Risorsa Interna', [inresource.outresource, inresource],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/inresources/edit.html.erb
<h1>Editing Risorsa Interna</h1>
<%= debug @inresource.outresource%>
<%= debug @inresource%>

<%= form_for [@inresource.outresource,@inresource] do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descr %><br />
    <%= f.text_area :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', outresource_inresources_path(@outresource) %>

app/views/inresources/index.html.erb
<h1>Listing Risorsa Interna</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descrizione</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inresources.each do |inresource| %>
  <tr>
    <td><%= inresource.name %></td>
    <td><%= inresource.descr %></td>

    <td><%= link_to 'Show', outresource_inresource_path(inresource.outresource, inresource) %></td>
    <td><%= link_to 'Edit', edit_outresource_inresource_path(inresource.outresource, inresource) %></td>
    <td><%= link_to 'Delete', outresource_inresource_path(inresource.outresource, inresource), :confirm => 'Are you sure?',:method => :delete %></td>
  </tr>
  
  
<% end %>
</table>

<%= link_to 'Aggiungi Nuova Risorsa Interna', new_outresource_inresource_path %>


<br />

app/views/inresources/new.html.erb
<h1>New Risorsa Interna</h1>

<%= render 'form' %>

<%= link_to 'Back', outresource_inresources_path(@outresource) %>

app/views/inresources/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Dettaglio Risorsa Interna</h2>

<p>
  <b>Nome:</b>
  <%= @inresource.name %>
</p>

<p>
  <b>Descrizione:</b>
  <%= @inresource.descr %>
</p>
<%= link_to 'Back', outresource_inresources_path(@outresource) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedResources</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/outresources/_form.html.erb
<%= form_for(@outresource) do |f| %>
  <% if @outresource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outresource.errors.count, "error") %> prohibited this Risorsa Esterna from being saved:</h2>

      <ul>
      <% @outresource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descr %><br />
    <%= f.text_field :descr %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outresources/edit.html.erb
<h1>Editing Risorsa Esterna</h1>

<%= render 'form' %>

<%= link_to 'Show', @outresource %> |
<%= link_to 'Back', outresources_path %>

app/views/outresources/index.html.erb
<h1>Listing Risorsa Esterna</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descrizione</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outresources.each do |outresource| %>
  <tr>
    <td><%= outresource.name %></td>
    <td><%= outresource.descr %></td>

    <td><%= link_to 'Show', outresource %></td>
    <td><%= link_to 'Edit', edit_outresource_path(outresource) %></td>
    <td><%= link_to 'Destroy', outresource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuova Risorsa Esterna', new_outresource_path %>

app/views/outresources/new.html.erb
<h1>New Risorsa Esterna</h1>

<%= render 'form' %>

<%= link_to 'Back', outresources_path %>

app/views/outresources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @outresource.name %>
</p>

<p>
  <b>Descrizione:</b>
  <%= @outresource.descr %>
</p>





<%= link_to 'Edit', edit_outresource_path(@outresource) %>
<%= link_to 'Back', outresources_path %>

<h2>Visualizza Elenco Risorse Interne</h2>
<%= link_to 'Visualizza', outresource_inresources_path(@outresource) %>